/*系统管理-菜单*/
CREATE TABLE `cm_user_info` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '用户信息表',
	`name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '用户名',
	`phone` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '电话',
	`sex` TINYINT NOT NULL DEFAULT '0' COMMENT '性别',
	`email` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '邮箱',
	`remark` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '备注',
	 
	`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
	`modify_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
);

